### Register user
POST http://localhost:5001/api/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "testuser3",
    "email": "test3@example.com",
    "password": "password123"
}

### Login user
# @name loginRequest
POST http://localhost:5001/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "test3@example.com",
    "password": "password123"
}

### User Profile
@authToken = {{loginRequest.response.body.$.token}}
GET http://localhost:5001/api/users/profile HTTP/1.1
Authorization: Bearer {{authToken}}

### Add Item
@authToken = {{loginRequest.response.body.$.token}}
POST http://localhost:5001/api/pantry HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "ingredient_id": 2,
    "quantity": "1",
    "unit": "large"
}

### Get All Items
@authToken = {{loginRequest.response.body.$.token}}
GET http://localhost:5001/api/pantry HTTP/1.1
Authorization: Bearer {{authToken}}

### Update Item
@authToken = {{loginRequest.response.body.$.token}}
PUT http://localhost:5001/api/pantry/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "quantity": "1",
    "unit": "medium"
}

### Remove Item
@authToken = {{loginRequest.response.body.$.token}}
DELETE http://localhost:5001/api/pantry/1 HTTP/1.1
Authorization: Bearer {{authToken}}

### Create Recipe
@authToken = {{loginRequest.response.body.$.token}}
POST http://localhost:5001/api/recipes HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Simple Pasta Dish",
  "description": "A quick and easy pasta dish.",
  "instructions": "1. Boil pasta. 2. Prepare sauce. 3. Mix and serve.",
  "prep_time_minutes": 10,
  "cook_time_minutes": 15,
  "difficulty": "Easy",
  "servings": 2,
  "image_url": "http://example.com/pasta.jpg",
  "ingredients": [
    { "name": "Pasta", "quantity": "200", "unit": "grams", "category": "Grain" },
    { "name": "Tomato Sauce", "quantity": "1", "unit": "can", "category": "Sauce" },
    { "ingredient_id": 3, "quantity": "2", "unit": "cloves" }
  ],
  "tags": [
    { "name": "Italian", "type": "cuisine" },
    { "name": "QuickMeal", "type": "teatime" }
  ]
}

### Get All Recipes
GET http://localhost:5001/api/recipes HTTP/1.1

### Get Single Recipe
GET http://localhost:5001/api/recipes/14 HTTP/1.1

### Update Recipe
@authToken = {{loginRequest.response.body.$.token}}
PUT http://localhost:5001/api/recipes/14 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title" : "Updated Super Pasta Dish V2",
  "difficulty": "Medium",
  "ingredients": [
    {"name": "Whole Wheat Pasta", "quantity": "250", "unit": "grams", "category": "Grain"},
    {"ingredient_id": 3, "quantity": "3", "unit": "cloves"} 
  ],
  "tags": [
    {"name": "Healthy", "type": "dietary"},
    {"tag_id": 1}
  ]
}

### Delete Recipe
@authToken = {{loginRequest.response.body.$.token}}
DELETE  http://localhost:5001/api/recipes/14 HTTP/1.1
Authorization: Bearer {{authToken}}


### Add to favorites
POST http://localhost:5001/api/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "recipe_id": 16
}
### Get favorites
GET http://localhost:5001/api/favorites HTTP/1.1
Authorization: Bearer {{authToken}}

### Delete favorites
DELETE http://localhost:5001/api/favorites/16 HTTP/1.1
Authorization: Bearer {{authToken}}